### ISSUE TITLE
No se almacenan los binarios compilados en el repositorio

### ISSUE THREAD

**Issue by evolentini** [m-scasserra/TP3TSSE#1]
En el repositorio solo debe almacenar código fuente, la carpeta `build` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio

@marianofino @rafaeloliva

**Comment by m-scasserra** [comment]
Arreglado en el commit [222f9c6](https://github.com/m-scasserra/TP3TSSE/commit/222f9c617080b5d8c88b24be08bf85f05c7c1b55)
